version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: yaxiong        # Set your database username
      POSTGRES_PASSWORD: password # Set your database password
      POSTGRES_DB: test_database      # Set your database name
    ports:
      - "5432:5432"                  # Map container port to host
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data

volumes:
  postgres_data:
    driver: local